### ISSUE TITLE
C implementation doesn't work with larger messages.

### ISSUE THREAD

**Issue by doino-gretchenliev** [tomerfiliba/reedsolomon#29]
I'm using the following code:
```python
import creedsolo as rs
prim = rs.find_prime_polys(c_exp=12, fast_primes=False, single=True)
rs.init_tables(prim=prim, c_exp=12)
```
The error thrown is:
```
    c_gf_log, c_gf_exp, c_field_charac = rs.init_tables(prim=prim, c_exp=12)
  File "creedsolo.pyx", line 203, in creedsolo.init_tables
OverflowError: value too large to convert to unsigned char
```
I'm trying to encode a file with 4095 sized chunks without using the additional 255 internal splittings. I've precalculated the polynomial numbers. So far I was able to encode, but not to decode the message:
```python
import creedsolo as rs
rs.init_tables()

mesecc = rs.rs_encode_msg(data, nsym, gen=gen[nsym]) # nsym = 123, len(data) = 3972
rmes, rmesecc, errata_pos = rs.rs_correct_msg(mesecc, nsym)
```
The error thrown is:
```
    rmes, rmesecc, errata_pos = rs.rs_correct_msg(mesecc, nsym)
  File "creedsolo.pyx", line 694, in creedsolo.rs_correct_msg
ValueError: Message is too long (4095 when max is 255)
```
Is there a way to encode 4095 chunks without hidden splitting?

**Comment by lrq3000** [comment]
Maybe related to #44

**Comment by lrq3000** [comment]
Ok so this is an inherent limitation because the C implementation only works with bytearrays, and bytearrays only support characters up to 255 IIRC. If you want to use higher galois fields, you need to use the pure python version, or rewrite the C implementation to use lists instead of bytearrays (which will be MUCH slower so this defeats the purpose and you are better off simply using the pure python version under PyPy).

About the lack of chunking, this is an issue also reported in #44, I will maybe merge the fix offered there.

**Comment by lrq3000** [comment]
Ah no there is no chunking anyway when you directly call the functions without the RSCodec object, it's only RSCodec that can do automatic chunking, not the functions.
