### ISSUE TITLE
The project description is inaccurate

### ISSUE THREAD

**Issue by mgorny** [tomerfiliba/reedsolomon#53]
I'm sorry for being picky but the description right now says:

> Pure-Python Reed Solomon encoder/decoder

However, the default install includes a C module, so that's not really "Pure-Python" and could lead to confusion. Would it be fine to change that to just "Python Reed Solomon encoder/decoder"?

**Comment by lrq3000** [comment]
Thank you for your suggestion. The C module is entirely optional and will always be, and on top it's transpiled from a statically typed python like *.pyx module, hence the description. The pure python version will remain the gild standard, the C implementation is only a bonus for those who want to get some more speed. The documentation already quite clearly specify the existence of the C module, and the fact it is complimentary.

**Comment by lrq3000** [comment]
Also for context, all other "Python Reed-Solomon codecs" are actually just wrappers around non-python implementations, so that you can't just edit the Python code, and the Python code is not sufficient.

Hence, to formalize my thought process, I consider as "Pure-Python" any Python package that does not require external non-Python tools to function. With this definition, which I believe is widely agreed on by other old time pythonistas, the outputs of a Python package do not matter. For example, I don't think anyone regard a Python package that generates DLLs or binaries, such as [scripts entry points](https://setuptools.pypa.io/en/latest/userguide/entry_point.html), as "non pure python". I think this is similar to a transpiled Cythonized extension.

And this definition is not an adhoc post rationalization, I use it for every other Python package I have published so far.

**Comment by mgorny** [comment]
A word of context to my use of the term: Linux distributions often treat Python packages that don't include any non-Python code as "noarch", i.e. roughly equivalent to "purelib" wheels. On the other hand, packages that do install C extensions need to be built and tested on every architecture separately (i.e. "platlib"). Having "pure Python" in the description here has led me to initially wrongly believe this is the package of the former category.

**Comment by lrq3000** [comment]
Thank you for your explanation.

Would the following rewriting of the description be OK?

> A universal errors-and-erasures Reed-Solomon Codec, including a pure python implementation and an optional speed-optimized Cython/C extension, based on the wonderful tutorial at [Wikiversity](http://en.wikiversity.org/wiki/Reed%E2%80%93Solomon_codes_for_coders), written by "Bobmath" and "LRQ3000". If you are just starting with Reed-Solomon error correction codes, the Wikiversity article is a good beginner's introduction.
> 
> This is a burst-type implementation, so that it supports any Galois field higher than 2^3, but not binary streams. Burst errors are non-random errors that more often happen on data storage mediums such as hard drives, hence this library is better indicated for data storage protection, and less for streams noise correction, although it can also be used for this purpose.

**Comment by mgorny** [comment]
Yes, that is much more descriptive, thank you.

**Comment by lrq3000** [comment]
Thank you for your feedback and your patience. It's now updated :-) I won't push to PyPi since no code has changed, but it will be pushed with the next bugfix! Have a great day and Merry Christmas!
